### ISSUE TITLE
Feature request: More selective method deleting

### ISSUE THREAD

**Issue by showlabor** [radarsat1/liblo#29]
Currently, AFAICT the only way to remove a method from a server is 
`void lo_server_del_method(lo_server s, const char *path, const char *typespec)`

This way you would end up deleting _every_ method that matches the path and typespec. If you have more than one method matching both all of them would be deleted from the server.

I'd like to be able to delete only a specific method e.g. by introducing

`void lo_server_del_method(lo_server s, lo_method method, const char *path, const char *typespec)`

So you can keep track of the methods an delete them selectively.
This would allow for much more dynamic method usage.

PS.: After looking into the source code it seems that path and typespec are already stored in a lo_method, so

`void lo_server_del_method(lo_server s, lo_method method)`

should already contain all needed information to delete a method.

Kind regards,
Felix

**Comment by radarsat1** [comment]
Hi, can you look at dellomethod branch? https://github.com/radarsat1/liblo/tree/dellomethod

I added the feature, and I agree it could be useful.  I can't think of a better name than,

    lo_server_del_lo_method()

but I am afraid this could be confusing.

**Comment by showlabor** [comment]
Thank you, it's great! Sure, the naming is a bit confusing. Maybe `lo_server_del_single_method()`?
The cleanest way was to rename the old `lo_server_del_method()` by something like  `lo_server_clear_path()`. But I guess that would break a lot of existing code. Too much trouble.

But at least in the C++ wrapper overloading allows for clean naming without problems.
BTW, could you please add a corresponding C++ method?

**Comment by radarsat1** [comment]
I was looking into this, but it appears that adding a return type to add_method() in C++ is far from trivial. I may look into it again in the future, but in the meantime I think it's best not to merge the change to the C code base until a C++ solution can be found, as I'd rather keep the two APIs equal in functionality.

**Comment by flv0** [comment]
What's the problem with the C++ return type exactly? 

Regarding the naming I also think having del_method and del_lo_method is very confusing. If breaking API is no option, using del_single_method or the like would be ok, however I agree that the initial naming is already confusing since it does not delete a single method, so I'd prefer the renaming @showlabor suggests, although it's really not important to me.

**Comment by flv0** [comment]
Ok I'm just reading the code and see there's a some complexity to it. Still what would the return value of add_method be used for?

**Comment by radarsat1** [comment]
Ok, I agree to the name "del_single_method", I guess that's more clear.  I used "del_lo_method" because it's deleting by lo_method handle, however, it's easily confused.. "del_single_method" would be clearer.  And yes, breaking API is strictly forbidden ;)

(Perhaps one day, a major version bump will introduce API/ABI breaking changes.. I have more than a few ideas of what could be cleaned up and benefit from that.)

As for the return type of add_method(), as you see there is some deep template magic happening in lo_cpp.h, specifically related to handling add_method() under a variety of circumstances.  I understand.. most.. of this deep magic, but the "enable_if" macro is not so easy to parse.  It actually uses the return type as a way of "marking" which "add_method" variety is to be called based on the signature of the provided handler function.  This enables a really cool API where you can call add_method() on a huge variety of callable functions and combinations of parameters. (see cpp_test.cpp).  However, it seems currently that it prevents actually returning a value from add_method(), which would be needed for keeping a lo_method handle for providing to del_method().  I'm not sure how to handle this, maybe another level of indirection (isn't that always the solution), but I'll need a good C++ template bashing session that might take a while.. I *really* like the way add_method() handles so many cases, so I'd rather keep that feature.

**Comment by showlabor** [comment]
BTW, I think the template magic could use a bit of documentation at least. IMHO, the way it is it is extremely hard to figure out what variations of add_method are available, what their parameters mean and how to use them.

**Comment by radarsat1** [comment]
You make a good point, there is no documentation at all for the C++ API.  However I just looked into adding it to the Doxygen manual, and it seems to clutter up the C API reference quite a bit.  Also, it seems non-obvious how to deal with macro-generated functions with complicated parameters -- doxygen just prints the parameter list without much more explanation, being not much less opaque than reading the source code.

I feel like maybe the C++ API should be documented more explicitly, with examples and explanations, because perhaps the `cpp_example.cpp` is not enough.  Actually liblo has been wanting for a more explicit written manual for quite a while, might be a fun project to work on for a future release.  I really don't find doxygen to be adequate documentation, and a series of tutorials or something would probably be a big help to users.

(Btw as much as I hate pointing users at "tests" as documentation, but all the possible calls for `lo::Server::add_method` are listed in `src/cpp_test.cpp`.  So that should be not a bad reference in the meantime.)

**Comment by radarsat1** [comment]
Finally figured out that I can just as well use a "phantom" argument instead of the return type for this purpose. Should be implemented now in a3700d8deb46fa85ddbb4d996cbc15a7f6ec6768.  Feel free to re-open if you find problems with it.
