### ISSUE TITLE
Compilation error with ENABLE_IPV6

### ISSUE THREAD

**Issue by kshpytsya** [radarsat1/liblo#56]
liblo-0.29
```
server.c: In function ‘lo_server_resolve_hostname’:
server.c:303:10: error: ‘it’ undeclared (first use in this function)
     for (it = ai; it; it = it->ai_next) {
          ^~
server.c:303:10: note: each undeclared identifier is reported only once for each function it appears in
server.c:303:15: error: ‘ai’ undeclared (first use in this function)
     for (it = ai; it; it = it->ai_next) {
               ^~
```

**Comment by radarsat1** [comment]
Thanks, it's a known issue that i haven't fixed yet.  Pull requests welcome ;)

Note that ENABLE_IPV6 is not currently recommended (per the README)

**Comment by sdegrande** [comment]
Please note that the broken IPv6 support seems to prevent the new release to be packaged in Fedora.
That's what I was told by the liblo package maintainer...

**Comment by sdegrande** [comment]
As a complement, in Fedora, the 0.28 version was build with ipv6 enabled.
Could be why the package maintainer is in need of a 'still working' ipv6 support before to update liblo.

**Comment by radarsat1** [comment]
I am working on it, but I just want to say that packagers should be the _last_ people enabling features clearly marked as not working.  I find that highly irresponsible.

**Comment by sdegrande** [comment]
Thank you for your work !

Being myself a FOSS project leader, I fully agree with you... I remember some not-always-pleasant-arguments with the package maintainer of a distribution known to apply its own patches to upstreams to remove or change features...

Do you expect a new release any time soon ?

**Comment by radarsat1** [comment]
Well I hesitate to do a release just for this but on the other hand it was my own oversight so maybe I'll do a point release just to have a properly working package. My main hesitation comes from the fact that not all of unit tests are passing with the flag enabled, so in that sense maybe it's actually better to leave a compilation error than to let users go around publishing half-broken builds that compile and run.   In that sense actually breaking the build for an unsupported flag is maybe a good thing, as it reveals these kinds of surprising situations that I wasn't aware of ;)

The thing is that it's not really obvious how to fix completely and I would need some help.  I'm happy to leave IPv6 multicast broken for now, since it gives a run-time error anyway, but even without the multicast test there is still something more subtle wrong, which I'd like to fix before doing a release I think.  Unfortunately I don't have a huge amount of time to work on it for the next 3 weeks or so.
